apiVersion: apps/v1
kind: Deployment
metadata:
  name: finbot-deploy
  namespace: default
spec:
  replicas: 2

  # ë¡¤ë§ ì—…ë°ì´íŠ¸(ë¬´ì¤‘ë‹¨ ë°°í¬) ì „ëµì„ ì •ì˜í•©ë‹ˆë‹¤.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # **í•µì‹¬**: ìƒˆ Podê°€ ì™„ì „íˆ ëœ° ë•Œê¹Œì§€ ê¸°ì¡´ PodëŠ” ì ˆëŒ€ ì¢…ë£Œí•˜ì§€ ì•ŠìŒ (ì˜¤ë¥˜ 0% ëª©í‘œ)
      maxUnavailable: 0

      # **í•µì‹¬**: ìƒˆë¡œìš´ ë²„ì „ì˜ Podë¥¼ í•œ ê°œ ë” ì¶”ê°€ë¡œ ìƒì„±í•  ìˆ˜ ìˆë„ë¡ í—ˆìš©
      maxSurge: 1
  selector:
    matchLabels:
      app: finbot
  template:
    metadata:
      labels:
        app: finbot
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: finbot
        # ğŸ‘‡ [ì¤‘ìš”] ë‹˜ì˜ Harbor ì£¼ì†Œë¡œ ë³€ê²½! (v1ì€ ì  í‚¨ìŠ¤ê°€ ë‚˜ì¤‘ì— v17, v18ë¡œ ë°”ê¿€ê²ë‹ˆë‹¤)
        image: 192.168.1.18/demo/finbot:v21
        ports:
        - containerPort: 80  # NginxëŠ” 80ë²ˆ í¬íŠ¸ë¥¼ ì”ë‹ˆë‹¤!
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5  # íŒŒë“œ ì‹œì‘ í›„ 5ì´ˆ ë’¤ë¶€í„° ì²´í¬
          periodSeconds: 5        # 5ì´ˆë§ˆë‹¤ ì²´í¬
