apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - name: my-web
        image: 192.168.1.18/demo/my-web:v1  # 아까 만든 이미지 주소
        ports:
        - containerPort: 80
