apiVersion: apps/v1
kind: Deployment
metadata:
  name: finbot-deploy
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: finbot
  template:
    metadata:
      labels:
        app: finbot
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: finbot
        image: 192.168.1.18/demo/finbot:v5
        ports:
        - containerPort: 80
