apiVersion: v1
kind: Service
metadata:
  name: finbot-svc
  namespace: default
spec:
  type: LoadBalancer # 또는 NodePort (기존에 쓰던 걸로 유지)
  selector:
    app: finbot
  ports:
    - protocol: TCP
      port: 80       # 서비스가 열어줄 포트
      targetPort: 80 # Nginx(컨테이너)가 듣고 있는 포트
