apiVersion: v1
kind: Service
metadata:
  name: finbot-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: finbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # 파이썬 앱 포트
